import React,{useEffect,useMemo,useState} from 'react';
import {SafeAreaView,View,Text,TextInput,ScrollView,Pressable,StyleSheet,ActivityIndicator,Alert,KeyboardAvoidingView,Platform} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {Ionicons} from '@expo/vector-icons';
import {SafeAreaProvider} from 'react-native-safe-area-context';
import {colors,shadow} from './src/theme';
import {books,categories} from './src/data';
import {Logo,Cover,Stars,Header,PrimaryButton,BottomNav,Empty} from './src/components/UI';

const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

function AppContent(){
 const [route,setRoute]=useState({name:'splash'}),[cart,setCart]=useState({}),[favorites,setFavorites]=useState([]),[query,setQuery]=useState('');
 useEffect(()=>{if(route.name==='splash'){const t=setTimeout(()=>setRoute({name:'login'}),1500);return()=>clearTimeout(t)}},[route.name]);
 const navigate=(name,params={})=>setRoute({name,...params});
 const add=id=>{setCart(c=>({...c,[id]:(c[id]||0)+1}));Alert.alert('Adicionado','Livro incluído no carrinho.')};
 const cartCount=Object.values(cart).reduce((a,b)=>a+b,0);
 const toggleFav=id=>setFavorites(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const props={navigate,route,cart,setCart,cartCount,favorites,toggleFav,add,query,setQuery};
 const screens={splash:Splash,login:Login,home:Home,categories:Categories};
 const Screen=screens[route.name]||(()=>null);
 return <SafeAreaView style={s.safe}><StatusBar style={route.name==='splash'?'light':'auto'}/><Screen {...props}/></SafeAreaView>;
}

function Splash(){return <View style={s.splash}><Logo light/><Text style={s.splashText}>A maior variedade de livros para você.</Text><ActivityIndicator size="large" color={colors.accent} style={{marginTop:45}}/></View>}
function Login({navigate}){const [email,setEmail]=useState(''),[pass,setPass]=useState(''),[error,setError]=useState('');const enter=()=>{if(!email.includes('@')||pass.length<4){setError('Informe um e-mail válido e uma senha com 4 caracteres.');return}navigate('home')};return <KeyboardAvoidingView style={s.page} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.login}><Logo/><Text style={s.title}>Bem-vindo de volta!</Text><Text style={s.muted}>Faça login para continuar</Text><View style={s.form}><TextInput style={s.input} placeholder="E-mail" keyboardType="email-address" autoCapitalize="none" value={email} onChangeText={setEmail}/><TextInput style={s.input} placeholder="Senha" secureTextEntry value={pass} onChangeText={setPass}/>{error?<Text style={s.error}>{error}</Text>:null}<PrimaryButton title="ENTRAR" onPress={enter}/><Text style={s.or}>ou</Text><PrimaryButton title="CONTINUAR COMO VISITANTE" outline onPress={()=>navigate('home')}/><Text style={s.center}>Não tem conta? <Text style={s.link}>Criar conta</Text></Text></View></ScrollView></KeyboardAvoidingView>}
function Layout({children,current,navigate,cartCount}){return <View style={s.page}>{children}<BottomNav current={current} navigate={navigate} cartCount={cartCount}/></View>}
function Home({navigate,cartCount,query,setQuery}){const shown=books.filter(b=>(b.title+b.author).toLowerCase().includes(query.toLowerCase()));return <Layout current="home" navigate={navigate} cartCount={cartCount}><ScrollView><View style={s.homeTop}><Logo light small/><Pressable onPress={()=>navigate('cart')}><Ionicons name="cart-outline" size={25} color="#fff"/></Pressable><View style={s.search}><Ionicons name="search" size={19} color={colors.muted}/><TextInput style={{flex:1}} placeholder="Buscar livros, autores, títulos..." value={query} onChangeText={setQuery}/></View></View><View style={s.body}><View style={s.banner}><View style={{flex:1}}><Text style={s.bannerTitle}>Livros que transformam ideias.</Text><Text style={s.bannerSub}>Ofertas para sua próxima leitura</Text></View><Ionicons name="library" size={70} color={colors.accent}/></View><SectionTitle title="Categorias" action={()=>navigate('categories')}/><ScrollView horizontal showsHorizontalScrollIndicator={false}>{categories.slice(0,5).map(c=><Pressable key={c.id} style={s.catSmall} onPress={()=>navigate('books',{category:c.id,title:c.name})}><View style={s.catIcon}><Ionicons name={c.icon} size={23} color={colors.primary}/></View><Text style={s.catSmallText}>{c.name}</Text></Pressable>)}</ScrollView><SectionTitle title={query?'Resultados':'Mais vendidos'} action={()=>navigate('books',{title:'Todos os livros'})}/><ScrollView horizontal showsHorizontalScrollIndicator={false}>{shown.slice(0,6).map(b=><Pressable key={b.id} style={s.bookGrid} onPress={()=>navigate('details',{id:b.id})}><Cover book={b}/><Text style={s.bookTitle} numberOfLines={2}>{b.title}</Text><Text style={s.price}>{money(b.price)}</Text></Pressable>)}</ScrollView></View></ScrollView></Layout>}
function SectionTitle({title,action}){return <View style={s.sectionHead}><Text style={s.sectionTitle}>{title}</Text><Pressable onPress={action}><Text style={s.link}>Ver todas</Text></Pressable></View>}
function Categories({navigate,cartCount}){return <Layout current="categories" navigate={navigate} cartCount={cartCount}><Header title="Categorias"/><ScrollView contentContainerStyle={s.body}>{categories.map(c=><Pressable key={c.id} style={s.categoryRow} onPress={()=>navigate('books',{category:c.id,title:c.name})}><View style={s.catIcon}><Ionicons name={c.icon} size={25} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{c.name}</Text><Text style={s.mutedSmall}>Ver livros</Text></View><Ionicons name="chevron-forward" size={21} color={colors.muted}/></Pressable>)}</ScrollView></Layout>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.primary},page:{flex:1,backgroundColor:colors.bg},splash:{flex:1,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},splashText:{color:'#fff',fontSize:16,marginTop:22},login:{flexGrow:1,backgroundColor:'#fff',padding:28,alignItems:'center',justifyContent:'center'},title:{fontSize:21,fontWeight:'800',color:colors.text,marginTop:30},muted:{color:colors.muted,marginTop:6},mutedSmall:{color:colors.muted,fontSize:12,marginVertical:4},form:{width:'100%',gap:13,marginTop:28},input:{height:53,borderWidth:1,borderColor:colors.border,borderRadius:9,paddingHorizontal:15,backgroundColor:'#fff'},error:{color:colors.danger,fontSize:12},or:{textAlign:'center',color:colors.muted},center:{textAlign:'center',marginTop:18,color:colors.muted},link:{color:colors.primary,fontWeight:'700'},homeTop:{backgroundColor:colors.primary,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',gap:14},search:{width:'100%',height:46,backgroundColor:'#fff',borderRadius:9,flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:8},body:{padding:16},banner:{minHeight:135,borderRadius:13,backgroundColor:'#124AA3',padding:20,flexDirection:'row',alignItems:'center',...shadow},bannerTitle:{color:'#fff',fontWeight:'900',fontSize:21,maxWidth:210},bannerSub:{color:'#DCE8FF',marginTop:8},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:24,marginBottom:12},sectionTitle:{fontSize:17,fontWeight:'800',color:colors.text},catSmall:{alignItems:'center',marginRight:13,width:64},catIcon:{width:48,height:48,borderRadius:13,backgroundColor:'#EAF1FF',alignItems:'center',justifyContent:'center'},catSmallText:{fontSize:10,textAlign:'center',marginTop:6},bookGrid:{width:100,marginRight:13},bookTitle:{fontWeight:'700',fontSize:13,marginTop:7,color:colors.text},price:{fontWeight:'900',color:colors.text,marginTop:7},categoryRow:{backgroundColor:'#fff',padding:14,borderRadius:12,marginBottom:11,flexDirection:'row',alignItems:'center',gap:13,...shadow},rowTitle:{fontWeight:'800',color:colors.text,fontSize:15}});

export default function App(){return <SafeAreaProvider><AppContent/></SafeAreaProvider>}