import React from 'react';
import {View,Text,Pressable,StyleSheet} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {colors,shadow} from '../theme';

export function Logo({light=false,small=false}){return <View style={s.logo}><Ionicons name="book" size={small?24:34} color={light?colors.accent:colors.primary}/><Text style={[s.logoText,{fontSize:small?22:31,color:light?colors.accent:colors.primary}]}>Saraiva</Text></View>}
export function Cover({book,large=false}){return <View style={[s.cover,{backgroundColor:book.color,width:large?150:76,height:large?210:108}]}><Ionicons name="book-outline" size={large?28:18} color="#fff"/><Text style={[s.coverText,{fontSize:large?18:11}]}>{book.tag}</Text></View>}
export function Stars({value}){return <View style={s.row}><Text style={{color:'#F5A000'}}>★★★★★</Text><Text style={s.rating}> {value}</Text></View>}
export function Header({title,onBack,right}){return <View style={s.header}>{onBack?<Pressable onPress={onBack} hitSlop={12}><Ionicons name="arrow-back" size={24} color="#fff"/></Pressable>:<View style={{width:24}}/>}<Text style={s.headerTitle}>{title}</Text>{right||<View style={{width:24}}/>}</View>}
export function PrimaryButton({title,onPress,outline=false,disabled=false}){return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,outline&&s.buttonOutline,disabled&&{opacity:.5},pressed&&{opacity:.8}]}><Text style={[s.buttonText,outline&&{color:colors.primary}]}>{title}</Text></Pressable>}
export function BottomNav({current,navigate,cartCount=0}){const items=[['home','Home','home-outline'],['categories','Categorias','grid-outline'],['favorites','Favoritos','heart-outline'],['cart','Carrinho','cart-outline'],['profile','Perfil','person-outline']];return <View style={s.nav}>{items.map(([key,label,icon])=><Pressable key={key} style={s.navItem} onPress={()=>navigate(key)}><View>{<Ionicons name={current===key?icon.replace('-outline',''):icon} size={22} color={current===key?colors.primary:colors.muted}/>} {key==='cart'&&cartCount>0?<View style={s.badge}><Text style={s.badgeText}>{cartCount}</Text></View>:null}</View><Text style={[s.navText,current===key&&{color:colors.primary,fontWeight:'700'}]}>{label}</Text></Pressable>)}</View>}
export function Empty({icon,title,text}){return <View style={s.empty}><Ionicons name={icon} size={55} color={colors.primary}/><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyText}>{text}</Text></View>}
const s=StyleSheet.create({row:{flexDirection:'row',alignItems:'center'},logo:{flexDirection:'row',alignItems:'center',gap:7},logoText:{fontWeight:'900'},cover:{borderRadius:7,padding:8,justifyContent:'space-between',...shadow},coverText:{color:'#fff',fontWeight:'900'},rating:{fontSize:12,color:colors.muted},header:{height:58,backgroundColor:colors.primary,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerTitle:{color:'#fff',fontSize:18,fontWeight:'800'},button:{backgroundColor:colors.primary,minHeight:50,borderRadius:9,alignItems:'center',justifyContent:'center',paddingHorizontal:18},buttonOutline:{backgroundColor:'#fff',borderWidth:1.5,borderColor:colors.primary},buttonText:{color:'#fff',fontWeight:'800'},nav:{height:68,backgroundColor:'#fff',borderTopWidth:1,borderColor:colors.border,flexDirection:'row',justifyContent:'space-around',paddingTop:8},navItem:{alignItems:'center',minWidth:55},navText:{fontSize:10,color:colors.muted,marginTop:3},badge:{position:'absolute',right:-10,top:-7,backgroundColor:colors.danger,minWidth:18,height:18,borderRadius:9,alignItems:'center',justifyContent:'center'},badgeText:{color:'#fff',fontSize:10,fontWeight:'800'},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:32},emptyTitle:{fontSize:20,fontWeight:'800',color:colors.text,marginTop:15},emptyText:{textAlign:'center',color:colors.muted,marginTop:7,lineHeight:21}});
